FROM ubuntu:18.04

RUN apt update ; apt install \
    python3 \
    python3-pip \ 
    r-base

RUN pip3 install \
     matplotlib \
     numpy \
     pandas \
     seaborn \ 
     sklearn

# import sys
# import sklearn
# import pandas as pd
# import gcsfs
# import seaborn as sns
# import numpy as np
# import matplotlib.pyplot as plt
# import math
# import random
# from sklearn.preprocessing import StandardScaler
# from sklearn.decomposition import PCA
# from sklearn.pipeline import Pipeline
